config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :ticks
  resources :tickers
  get 'welcome/index'

  resources :articles do
    end

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tick.rb
class Tick < ApplicationRecord
  belongs_to :ticker
end

app/models/ticker.rb
class Ticker < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  before_action :set_ticker, only: %i[ show edit update destroy ]

  # GET /tickers or /tickers.json
  def index
    @tickers = Ticker.all
  end

  # GET /tickers/1 or /tickers/1.json
  def show
  end

  # GET /tickers/new
  def new
    @ticker = Ticker.new
  end

  # GET /tickers/1/edit
  def edit
  end

  # POST /tickers or /tickers.json
  def create
    @ticker = Ticker.new(ticker_params)

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to ticker_url(@ticker), notice: "Ticker was successfully created." }
        format.json { render :show, status: :created, location: @ticker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickers/1 or /tickers/1.json
  def update
    respond_to do |format|
      if @ticker.update(ticker_params)
        format.html { redirect_to ticker_url(@ticker), notice: "Ticker was successfully updated." }
        format.json { render :show, status: :ok, location: @ticker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickers/1 or /tickers/1.json
  def destroy
    @ticker.destroy

    respond_to do |format|
      format.html { redirect_to tickers_url, notice: "Ticker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticker
      @ticker = Ticker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticker_params
      params.require(:ticker).permit(:name, :slug, :url, :description, :units)
    end
end

app/controllers/ticks_controller.rb
class TicksController < ApplicationController
  before_action :set_tick, only: %i[ show edit update destroy ]

  # GET /ticks or /ticks.json
  def index
    @ticks = Tick.all
  end

  # GET /ticks/1 or /ticks/1.json
  def show
  end

  # GET /ticks/new
  def new
    @tick = Tick.new
  end

  # GET /ticks/1/edit
  def edit
  end

  # POST /ticks or /ticks.json
  def create
    @tick = Tick.new(tick_params)

    respond_to do |format|
      if @tick.save
        format.html { redirect_to tick_url(@tick), notice: "Tick was successfully created." }
        format.json { render :show, status: :created, location: @tick }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticks/1 or /ticks/1.json
  def update
    respond_to do |format|
      if @tick.update(tick_params)
        format.html { redirect_to tick_url(@tick), notice: "Tick was successfully updated." }
        format.json { render :show, status: :ok, location: @tick }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticks/1 or /ticks/1.json
  def destroy
    @tick.destroy

    respond_to do |format|
      format.html { redirect_to ticks_url, notice: "Tick was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tick
      @tick = Tick.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tick_params
      params.require(:tick).permit(:ticker_id, :value, :delta_day, :delta_week, :delta_month)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/ticks_helper.rb
module TicksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickerville</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickers/_form.html.erb
<%= form_with(model: ticker) do |form| %>
  <% if ticker.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
        <% ticker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :units, style: "display: block" %>
    <%= form.text_field :units %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickers/_ticker.html.erb
<div id="<%= dom_id ticker %>">
  <p>
    <strong>Name:</strong>
    <%= ticker.name %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= ticker.slug %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= ticker.url %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= ticker.description %>
  </p>

  <p>
    <strong>Units:</strong>
    <%= ticker.units %>
  </p>

</div>

app/views/tickers/edit.html.erb
<h1>Editing ticker</h1>

<%= render "form", ticker: @ticker %>

<br>

<div>
  <%= link_to "Show this ticker", @ticker %> |
  <%= link_to "Back to tickers", tickers_path %>
</div>

app/views/tickers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickers</h1>

<div id="tickers">
  <% @tickers.each do |ticker| %>
    <%= render ticker %>
    <p>
      <%= link_to "Show this ticker", ticker %>
    </p>
  <% end %>
</div>

<%= link_to "New ticker", new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New ticker</h1>

<%= render "form", ticker: @ticker %>

<br>

<div>
  <%= link_to "Back to tickers", tickers_path %>
</div>

app/views/tickers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticker %>

<div>
  <%= link_to "Edit this ticker", edit_ticker_path(@ticker) %> |
  <%= link_to "Back to tickers", tickers_path %>

  <%= button_to "Destroy this ticker", @ticker, method: :delete %>
</div>

app/views/ticks/_form.html.erb
<%= form_with(model: tick) do |form| %>
  <% if tick.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tick.errors.count, "error") %> prohibited this tick from being saved:</h2>

      <ul>
        <% tick.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ticker_id, style: "display: block" %>
    <%= form.text_field :ticker_id %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :delta_day, style: "display: block" %>
    <%= form.text_field :delta_day %>
  </div>

  <div>
    <%= form.label :delta_week, style: "display: block" %>
    <%= form.text_field :delta_week %>
  </div>

  <div>
    <%= form.label :delta_month, style: "display: block" %>
    <%= form.text_field :delta_month %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ticks/_tick.html.erb
<div id="<%= dom_id tick %>">
  <p>
    <strong>Ticker:</strong>
    <%= tick.ticker_id %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= tick.value %>
  </p>

  <p>
    <strong>Delta day:</strong>
    <%= tick.delta_day %>
  </p>

  <p>
    <strong>Delta week:</strong>
    <%= tick.delta_week %>
  </p>

  <p>
    <strong>Delta month:</strong>
    <%= tick.delta_month %>
  </p>

</div>

app/views/ticks/edit.html.erb
<h1>Editing tick</h1>

<%= render "form", tick: @tick %>

<br>

<div>
  <%= link_to "Show this tick", @tick %> |
  <%= link_to "Back to ticks", ticks_path %>
</div>

app/views/ticks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ticks</h1>

<div id="ticks">
  <% @ticks.each do |tick| %>
    <%= render tick %>
    <p>
      <%= link_to "Show this tick", tick %>
    </p>
  <% end %>
</div>

<%= link_to "New tick", new_tick_path %>

app/views/ticks/new.html.erb
<h1>New tick</h1>

<%= render "form", tick: @tick %>

<br>

<div>
  <%= link_to "Back to ticks", ticks_path %>
</div>

app/views/ticks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tick %>

<div>
  <%= link_to "Edit this tick", edit_tick_path(@tick) %> |
  <%= link_to "Back to ticks", ticks_path %>

  <%= button_to "Destroy this tick", @tick, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to "Articles", articles_path %>